spring:
  profiles:
    default: local

  config:
    import:
      - db.yml
      - cache.yml
---
spring:
  config:
    activate:
      on-profile: local
server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 5
  data:
    redis:
      host: 127.0.0.1
      port: 6379
---
spring:
  config:
    activate:
      on-profile: test

