spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lock_sys
    username: "root"
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 25
      maximum-pool-size: 25

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql
      encoding: UTF-8
